name        : libotr
version     : 4.1.1
release     : 6
source     :
    - https://otr.cypherpunks.ca/libotr-4.1.1.tar.gz : 8b3b182424251067a952fb4e6c7b95a21e644fbb27fbd5f8af2b2ed87ca419f5
license     :
    - GPL-2.0
summary     : Off The Record Messaging library
builddeps   :
    - libgcrypt-devel
patterns    :
    - bin:
        - /usr/share/man
        - /usr/bin
description : |
    Off The Record Messaging (OTR) allows private communications over instant messaging by providing encryption, authentication, deniability, and secrecy.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
